---
- name: Ensure that the DNS server is set to the domain controller
  ansible.windows.win_dns_client:
    adapter_names: "*"
    ipv4_addresses:
      - "{{ dns_server }}"

- name: Ensure that the host is joined to the domain
  ansible.windows.win_domain_membership:
    dns_domain_name: "{{ dns_domain_name }}"
    domain_admin_user: "Admin@{{ dns_domain_name }}"
    domain_admin_password: "{{ ansible_password }}"
    state: domain
  register: domain_state

- name: Reboot if required by joining domain
  ansible.windows.win_reboot:
  when: domain_state.reboot_required
