---
- name: Ensure that inventory machines are deployed
  community.vmware.vmware_guest:
    template: "{{ vm_template }}"
    folder: "{{ vm_folder }}"
    name: "{{ inventory_hostname }}"
    wait_for_ip_address: true
    datacenter: "{{ vm_datacenter }}"
    validate_certs: false
    cluster: "{{ vm_cluster }}"
    state: poweredon
    networks:
      - name: "{{ vm_network }}"
        type: static
        ip: "{{ ansible_host }}"
        netmask: "{{ vm_netmask }}"
        gateway: "{{ vm_gateway }}"
        dns_servers:
          - "{{ vm_dns }}"
    customization:
      password: "{{ ansible_password }}"
      autologon: true
      runonce:
        - powershell.exe -command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 -OutFile C:\ConfigureRemotingForAnsible.ps1"  # yamllint disable-line rule:line-length
        - powershell.exe -ExecutionPolicy Unrestricted -File C:\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
  register: vminfo
  delegate_to: localhost

- name: Wait for the system to respond to management
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: "{{ ansible_port }}"
    delay: 60
    timeout: 900
  when: vminfo.changed
  delegate_to: localhost
