---
- name: Ensure that inventory machines are deployed
  community.vmware.vmware_guest:
    template: "/Central/vm/Ansible/Nick A/Templates/WINDOWS_SERVER_2019"
    folder: "/Central/vm/Ansible/Nick A/Demos"
    name: "{{ inventory_hostname }}"
    wait_for_ip_address: true
    datacenter: "Central"
    validate_certs: false
    cluster: "Tigers"
    state: poweredon
    networks:
      - name: "Nick"
        type: static
        ip: "{{ ansible_host }}"
        netmask: 255.255.255.0
        gateway: 10.1.19.1
        dns_servers:
          - 10.1.19.1
    customization:
      password: "{{ ansible_password }}"
      autologoncount: 10
      autologon: true
      runonce:
        - powershell.exe -command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 -OutFile C:\ConfigureRemotingForAnsible.ps1"  # yamllint disable-line rule:line-length
        - powershell.exe -ExecutionPolicy Unrestricted -File C:\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
  register: vminfo
  delegate_to: localhost

- name: Wait for the system to respond to management
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: "{{ ansible_port }}"
    delay: 60
    timeout: 900
  when: vminfo.changed
  delegate_to: localhost
